version: "3"

services:
  dtl:
    image: ericlee42/metis-dtl:20211205
    entrypoint: ./dtl.sh
    restart: unless-stopped
    stop_grace_period: 2m
    environment:
      URL: https://metis-us-east-2-mainnet-json.s3.us-east-2.amazonaws.com/addresses.json
      DATA_TRANSPORT_LAYER__L1_RPC_ENDPOINT: https://eth-mainnet.alchemyapi.io/v2/JTKrG8NyONZuqojbmWT743rjmQpPNCYP
      DATA_TRANSPORT_LAYER__L2_RPC_ENDPOINT: https://andromeda.metis.io/?owner=1088
      DATA_TRANSPORT_LAYER__L2_CHAIN_ID: 1088
      DATA_TRANSPORT_LAYER__CONFIRMATIONS: 1
      DATA_TRANSPORT_LAYER__SYNC_FROM_L1: "false"
      DATA_TRANSPORT_LAYER__SYNC_FROM_L2: "true"
      DATA_TRANSPORT_LAYER__DB_PATH: /data/db
      DATA_TRANSPORT_LAYER__SERVER_PORT: "7878"
      DATA_TRANSPORT_LAYER__TRANSACTIONS_PER_POLLING_INTERVAL: "1000"
      DATA_TRANSPORT_LAYER__POLLING_INTERVAL: "100"
      DATA_TRANSPORT_LAYER__LOGS_PER_POLLING_INTERVAL: "2000"
      DATA_TRANSPORT_LAYER__DANGEROUSLY_CATCH_ALL_ERRORS: "true"
      DATA_TRANSPORT_LAYER__SERVER_HOSTNAME: "0.0.0.0"
    ports:
      - 7878:7878
    volumes:
      - $PWD/chaindata/dtl:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "10"

  l2geth:
    image: ericlee42/metis-l2geth-peer:20211216
    entrypoint: sh ./geth-peer.sh
    restart: unless-stopped
    stop_grace_period: 2m
    env_file:
      - ./geth-peer.env
    environment:
      URL: https://metis-us-east-2-mainnet-json.s3.us-east-2.amazonaws.com/addresses.json
      ROLLUP_POLL_INTERVAL_FLAG: 30000ms
      MVM_GAS_ORACLE_PRICE: 1000
      MVM_GAS_ORACLE_ADDRESS: "0x4200000000000000000000000000000000000006"
      BLOCK_SIGNER_KEY: "6587ae678cf4fc9a33000cdbf9f35226b71dcc6a4684a31203241f9bcfd55d27"
      BLOCK_SIGNER_ADDRESS: "0x00000398232E2064F896018496b4b44b3D62751F"
      ROLLUP_STATE_DUMP_PATH: https://metis-us-east-2-mainnet-json.s3.us-east-2.amazonaws.com/state-dump.latest.json
      ROLLUP_CLIENT_HTTP: http://dtl:7878
      L2_URL: https://andromeda.metis.io/?owner=1088
      ETH1_CTC_DEPLOYMENT_HEIGHT: 8
      L2_HOST_IP: "34.230.124.36"
    volumes:
      - $PWD/chaindata/l2geth:/root/.ethereum
      - $PWD/geth-peer.sh:/geth-peer.sh
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303
